name: Ping Render Backend

on:
  schedule:
    # Schedule to run every hour
    - cron: "0 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Ping Script
        run: bash scripts/ping.sh
